// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.2
// source: protofiles/center.proto

package protofiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailableKeysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Qty int64 `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
}

func (x *AvailableKeysReq) Reset() {
	*x = AvailableKeysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_center_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableKeysReq) ProtoMessage() {}

func (x *AvailableKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_center_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableKeysReq.ProtoReflect.Descriptor instead.
func (*AvailableKeysReq) Descriptor() ([]byte, []int) {
	return file_protofiles_center_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableKeysReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AvailableKeysReq) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

var File_protofiles_center_proto protoreflect.FileDescriptor

var file_protofiles_center_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x10, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x71, 0x74, 0x79, 0x32, 0x54, 0x0a, 0x0a, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x46, 0x0a, 0x08, 0x53, 0x65, 0x6e,
	0x64, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65,
	0x71, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x6f, 0x66, 0x69, 0x77, 0x69, 0x77, 0x69, 0x77, 0x69, 0x2f, 0x32, 0x30, 0x32, 0x33, 0x5f,
	0x31, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x62, 0x75,
	0x70, 0x2d, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x2f, 0x54, 0x61, 0x72, 0x65, 0x61, 0x2d,
	0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_center_proto_rawDescOnce sync.Once
	file_protofiles_center_proto_rawDescData = file_protofiles_center_proto_rawDesc
)

func file_protofiles_center_proto_rawDescGZIP() []byte {
	file_protofiles_center_proto_rawDescOnce.Do(func() {
		file_protofiles_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_center_proto_rawDescData)
	})
	return file_protofiles_center_proto_rawDescData
}

var file_protofiles_center_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protofiles_center_proto_goTypes = []interface{}{
	(*AvailableKeysReq)(nil), // 0: protofiles.AvailableKeysReq
}
var file_protofiles_center_proto_depIdxs = []int32{
	0, // 0: protofiles.NotifyKeys.SendKeys:input_type -> protofiles.AvailableKeysReq
	0, // 1: protofiles.NotifyKeys.SendKeys:output_type -> protofiles.AvailableKeysReq
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_center_proto_init() }
func file_protofiles_center_proto_init() {
	if File_protofiles_center_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_center_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableKeysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_center_proto_goTypes,
		DependencyIndexes: file_protofiles_center_proto_depIdxs,
		MessageInfos:      file_protofiles_center_proto_msgTypes,
	}.Build()
	File_protofiles_center_proto = out.File
	file_protofiles_center_proto_rawDesc = nil
	file_protofiles_center_proto_goTypes = nil
	file_protofiles_center_proto_depIdxs = nil
}
