// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: protofiles/servicios.proto

package protofiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// mensajes OMS
// Continente --> OMS: informa nombre de persona y su estado
type InfoPersonaContinenteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre      string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	EsInfectado bool   `protobuf:"varint,2,opt,name=esInfectado,proto3" json:"esInfectado,omitempty"`
}

func (x *InfoPersonaContinenteReq) Reset() {
	*x = InfoPersonaContinenteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoPersonaContinenteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPersonaContinenteReq) ProtoMessage() {}

func (x *InfoPersonaContinenteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPersonaContinenteReq.ProtoReflect.Descriptor instead.
func (*InfoPersonaContinenteReq) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{0}
}

func (x *InfoPersonaContinenteReq) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *InfoPersonaContinenteReq) GetEsInfectado() bool {
	if x != nil {
		return x.EsInfectado
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{1}
}

// ONU --> OMS: informa estado de todas las personas
type InfoPersonasCondicionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EsInfectado bool `protobuf:"varint,1,opt,name=esInfectado,proto3" json:"esInfectado,omitempty"`
}

func (x *InfoPersonasCondicionReq) Reset() {
	*x = InfoPersonasCondicionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoPersonasCondicionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPersonasCondicionReq) ProtoMessage() {}

func (x *InfoPersonasCondicionReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPersonasCondicionReq.ProtoReflect.Descriptor instead.
func (*InfoPersonasCondicionReq) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{2}
}

func (x *InfoPersonasCondicionReq) GetEsInfectado() bool {
	if x != nil {
		return x.EsInfectado
	}
	return false
}

type InfoPersonasCondicionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombres     []string `protobuf:"bytes,1,rep,name=nombres,proto3" json:"nombres,omitempty"`
	EsInfectado []bool   `protobuf:"varint,2,rep,packed,name=esInfectado,proto3" json:"esInfectado,omitempty"`
}

func (x *InfoPersonasCondicionResp) Reset() {
	*x = InfoPersonasCondicionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoPersonasCondicionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPersonasCondicionResp) ProtoMessage() {}

func (x *InfoPersonasCondicionResp) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPersonasCondicionResp.ProtoReflect.Descriptor instead.
func (*InfoPersonasCondicionResp) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{3}
}

func (x *InfoPersonasCondicionResp) GetNombres() []string {
	if x != nil {
		return x.Nombres
	}
	return nil
}

func (x *InfoPersonasCondicionResp) GetEsInfectado() []bool {
	if x != nil {
		return x.EsInfectado
	}
	return nil
}

// Data Node
// OMS --> Datanode: solicita nombre de persona de acuerdo al id
type NombrePersonaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NombrePersonaReq) Reset() {
	*x = NombrePersonaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NombrePersonaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NombrePersonaReq) ProtoMessage() {}

func (x *NombrePersonaReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NombrePersonaReq.ProtoReflect.Descriptor instead.
func (*NombrePersonaReq) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{4}
}

func (x *NombrePersonaReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NombrePersonaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *NombrePersonaResp) Reset() {
	*x = NombrePersonaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NombrePersonaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NombrePersonaResp) ProtoMessage() {}

func (x *NombrePersonaResp) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NombrePersonaResp.ProtoReflect.Descriptor instead.
func (*NombrePersonaResp) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{5}
}

func (x *NombrePersonaResp) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type DatosIdNombreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *DatosIdNombreReq) Reset() {
	*x = DatosIdNombreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_servicios_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatosIdNombreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosIdNombreReq) ProtoMessage() {}

func (x *DatosIdNombreReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_servicios_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosIdNombreReq.ProtoReflect.Descriptor instead.
func (*DatosIdNombreReq) Descriptor() ([]byte, []int) {
	return file_protofiles_servicios_proto_rawDescGZIP(), []int{6}
}

func (x *DatosIdNombreReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DatosIdNombreReq) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

var File_protofiles_servicios_proto protoreflect.FileDescriptor

var file_protofiles_servicios_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x18, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x18, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x61,
	0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x65,
	0x63, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x57, 0x0a, 0x19, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x08, 0x52, 0x0b, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x65, 0x63, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x22,
	0x0a, 0x10, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22,
	0x3a, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x49, 0x64, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x32, 0xad, 0x01, 0x0a, 0x03,
	0x4f, 0x4d, 0x53, 0x12, 0x4b, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x59, 0x0a, 0x0a, 0x61, 0x73, 0x6b, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x73, 0x12, 0x24,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x32, 0x97, 0x01, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64,
	0x49, 0x64, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x49, 0x64, 0x4e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0b, 0x61, 0x73, 0x6b,
	0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x69, 0x77, 0x69, 0x77, 0x69, 0x77, 0x69, 0x2f, 0x32,
	0x30, 0x32, 0x33, 0x5f, 0x32, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x2f, 0x74, 0x72, 0x65,
	0x65, 0x2f, 0x73, 0x6f, 0x66, 0x69, 0x77, 0x69, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x54, 0x61, 0x72,
	0x65, 0x61, 0x2d, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_servicios_proto_rawDescOnce sync.Once
	file_protofiles_servicios_proto_rawDescData = file_protofiles_servicios_proto_rawDesc
)

func file_protofiles_servicios_proto_rawDescGZIP() []byte {
	file_protofiles_servicios_proto_rawDescOnce.Do(func() {
		file_protofiles_servicios_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_servicios_proto_rawDescData)
	})
	return file_protofiles_servicios_proto_rawDescData
}

var file_protofiles_servicios_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protofiles_servicios_proto_goTypes = []interface{}{
	(*InfoPersonaContinenteReq)(nil),  // 0: protofiles.InfoPersonaContinenteReq
	(*Empty)(nil),                     // 1: protofiles.Empty
	(*InfoPersonasCondicionReq)(nil),  // 2: protofiles.InfoPersonasCondicionReq
	(*InfoPersonasCondicionResp)(nil), // 3: protofiles.InfoPersonasCondicionResp
	(*NombrePersonaReq)(nil),          // 4: protofiles.NombrePersonaReq
	(*NombrePersonaResp)(nil),         // 5: protofiles.NombrePersonaResp
	(*DatosIdNombreReq)(nil),          // 6: protofiles.DatosIdNombreReq
}
var file_protofiles_servicios_proto_depIdxs = []int32{
	0, // 0: protofiles.OMS.sendNombreEstado:input_type -> protofiles.InfoPersonaContinenteReq
	2, // 1: protofiles.OMS.askNombres:input_type -> protofiles.InfoPersonasCondicionReq
	6, // 2: protofiles.dataNode.sendIdEstado:input_type -> protofiles.DatosIdNombreReq
	4, // 3: protofiles.dataNode.askNombreId:input_type -> protofiles.NombrePersonaReq
	1, // 4: protofiles.OMS.sendNombreEstado:output_type -> protofiles.Empty
	3, // 5: protofiles.OMS.askNombres:output_type -> protofiles.InfoPersonasCondicionResp
	1, // 6: protofiles.dataNode.sendIdEstado:output_type -> protofiles.Empty
	5, // 7: protofiles.dataNode.askNombreId:output_type -> protofiles.NombrePersonaResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_servicios_proto_init() }
func file_protofiles_servicios_proto_init() {
	if File_protofiles_servicios_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_servicios_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoPersonaContinenteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_servicios_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_servicios_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoPersonasCondicionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_servicios_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoPersonasCondicionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_servicios_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NombrePersonaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_servicios_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NombrePersonaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_servicios_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatosIdNombreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_servicios_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protofiles_servicios_proto_goTypes,
		DependencyIndexes: file_protofiles_servicios_proto_depIdxs,
		MessageInfos:      file_protofiles_servicios_proto_msgTypes,
	}.Build()
	File_protofiles_servicios_proto = out.File
	file_protofiles_servicios_proto_rawDesc = nil
	file_protofiles_servicios_proto_goTypes = nil
	file_protofiles_servicios_proto_depIdxs = nil
}
